
name: orthanc-stack

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  orthanc:
    image: orthancteam/orthanc-plugins:24.10
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ORTHANC__NAME: ${ORTHANC_NAME}
      ORTHANC__DICOM_AET: ${ORTHANC_AET}
      ORTHANC__DICOM_PORT: "4242"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # DICOM storage (bind to OneDrive‑synced path) — portable by changing .env
      - type: bind
        source: ${ONEDRIVE_ROOT}/orthanc-storage
        target: /var/lib/orthanc/storage
      # Keep LevelDB index local (NOT in OneDrive) for reliability & performance
      - orthanc_index:/var/lib/orthanc/index
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    ports:
      - "8042:8042"   # Orthanc UI/REST (http)
      - "4242:4242"   # DICOM C-STORE SCP
    restart: unless-stopped

  # Nightly logical backups of Postgres into OneDrive folder
  pg_backup:
    image: prodrigestivill/postgres-backup-local:16
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: "${PG_BACKUP_CRON}"
      BACKUP_DIR: /backups
      BACKUP_KEEP_DAYS: "${PG_BACKUP_KEEP_DAYS}"
      BACKUP_KEEP_WEEKS: "${PG_BACKUP_KEEP_WEEKS}"
      BACKUP_KEEP_MONTHS: "${PG_BACKUP_KEEP_MONTHS}"
      POSTGRES_EXTRA_OPTS: "--format=custom --verbose"
    volumes:
      - type: bind
        source: ${ONEDRIVE_ROOT}/pg-backups
        target: /backups
    restart: unless-stopped

volumes:
  pg_data:
  orthanc_index: